# Generated by Django 4.1.4 on 2022-12-24 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reciever',
        ),
    ]
